-- A.REST_ID를 기준으로 그룹화를 한다.
-- HAVING을 통해 그룹화한 곳에 조건부여
SELECT 
    A.REST_ID, 
    A.REST_NAME, 
    A.FOOD_TYPE, 
    A.FAVORITES,
    A.ADDRESS,
    ROUND(AVG(B.REVIEW_SCORE), 2) as SCORE 
FROM REST_INFO as A
INNER 
JOIN REST_REVIEW as B
ON A.REST_ID = B.REST_ID
GROUP BY A.REST_ID
HAVING A.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, A.FAVORITES DESC;